"""Playwright-driven client for the official Pokemon Event Locator's
internal API (an OutSystems Reactive Web app at events.pokemon.com).

The endpoint sits behind both Imperva/Incapsula and Akamai Bot Manager (the
`reese84` sensor cookie). Akamai's sensor token is generated by real
in-browser JS and is validated against the request's own TLS/HTTP2
fingerprint, so replaying captured cookies/headers with a plain `requests`
client is fragile. Instead this drives headless Chromium through the real
page once (letting the site's own JS complete the anti-bot challenge), then
issues the API call as an in-page `fetch()` via `page.evaluate()` - that
runs inside the already-authenticated page's own JS engine, so cookies,
TLS/H2 fingerprint, and Origin/Referer all match a real browser exactly,
with zero manual replication.
"""

from __future__ import annotations

import time
import urllib.parse
from dataclasses import dataclass

from playwright.sync_api import sync_playwright

EVENT_LOCATOR_URL = "https://events.pokemon.com/EventLocator/"
API_PATH = "/EventLocator/screenservices/EventLocator/MainFlow/Home/DataActionGetEventList"
COOKIE_WAIT_TIMEOUT = 10.0
COOKIE_WAIT_INTERVAL = 0.25


@dataclass
class SearchParams:
    """Drives both the initial page navigation and the POST payload, so the
    two can never drift apart - the real site's Referer header on its own
    POST reflects the same query params used to load the page."""

    latitude: str
    longitude: str
    range_km: str
    start_date: str
    filters: str = "vg"
    locale: str = "it-IT"

    def to_url(self) -> str:
        query = urllib.parse.urlencode(
            {
                "locale": self.locale,
                "range": self.range_km,
                "startdate": self.start_date,
                "iskm": "true",
                "latitude": self.latitude,
                "longitude": self.longitude,
                "filters": self.filters,
            }
        )
        return f"{EVENT_LOCATOR_URL}?{query}"


class SessionNotReadyError(RuntimeError):
    """Raised when the anti-bot challenge cookies never showed up in time."""


class PokemonEventLocatorClient:
    def __init__(self, headless: bool = False):
        """Defaults to headed: testing showed the site's WAF (Incapsula, with
        an Akamai-style `reese84` sensor cookie) 403s the app's own internal
        API calls when it detects a GPU-less/headless rendering fingerprint,
        even though static assets load fine either way. Headed Chromium
        (with a real or virtual display) avoids that. See tool/README.md."""
        self.headless = headless
        self._playwright = None
        self._browser = None
        self._context = None
        self._page = None

    def __enter__(self) -> "PokemonEventLocatorClient":
        self._playwright = sync_playwright().start()
        self._browser = self._playwright.chromium.launch(headless=self.headless)
        self._context = self._browser.new_context(
            geolocation={"latitude": 45.4642, "longitude": 9.1900},
            permissions=["geolocation"],
        )
        self._page = self._context.new_page()
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        if self._context is not None:
            self._context.close()
        if self._browser is not None:
            self._browser.close()
        if self._playwright is not None:
            self._playwright.stop()

    def bootstrap(self, search: SearchParams) -> None:
        """Navigate to the real page and wait for the anti-bot cookies to
        show up. `networkidle` is not used here - this page keeps background
        network activity going (map tiles, analytics) that can prevent the
        network from ever going fully idle, so `domcontentloaded` plus
        explicit cookie polling is the more reliable readiness signal."""
        self._page.goto(search.to_url(), wait_until="domcontentloaded", timeout=45000)
        self._wait_for_cookie("reese84")
        self._wait_for_cookie("nr2Users")

    def _wait_for_cookie(self, name: str) -> str:
        deadline = time.monotonic() + COOKIE_WAIT_TIMEOUT
        while time.monotonic() < deadline:
            for cookie in self._context.cookies():
                if cookie["name"] == name:
                    return cookie["value"]
            time.sleep(COOKIE_WAIT_INTERVAL)
        raise SessionNotReadyError(
            f"Cookie {name!r} never appeared within {COOKIE_WAIT_TIMEOUT}s - "
            "the anti-bot challenge likely didn't complete."
        )

    def _read_csrf_token(self) -> str:
        """The `nr2Users` cookie the server sets on page load encodes
        `crf=<token>;uid=...;unm=...` (URL-encoded) - this is a classic
        double-submit-cookie CSRF pattern where the same value must be
        echoed back as the X-Csrftoken header on POSTs. Read fresh every
        call rather than hardcoded, since it's session-specific."""
        for cookie in self._context.cookies():
            if cookie["name"] == "nr2Users":
                decoded = urllib.parse.unquote(cookie["value"])
                for part in decoded.split(";"):
                    if part.startswith("crf="):
                        token = part[len("crf="):]
                        if token:
                            return token
        raise SessionNotReadyError("nr2Users cookie missing or has no crf= segment.")

    def post_json(self, payload: dict, max_retries: int = 2) -> dict:
        csrf_token = self._read_csrf_token()
        last_error: Exception | None = None
        for attempt in range(1, max_retries + 1):
            try:
                result = self._page.evaluate(
                    """async ({ path, payload, csrfToken }) => {
                        const res = await fetch(path, {
                            method: "POST",
                            headers: {
                                "Accept": "application/json",
                                "Content-Type": "application/json; charset=UTF-8",
                                "X-Csrftoken": csrfToken,
                            },
                            body: JSON.stringify(payload),
                        });
                        const text = await res.text();
                        return { ok: res.ok, status: res.status, text };
                    }""",
                    {"path": API_PATH, "payload": payload, "csrfToken": csrf_token},
                )
            except Exception as exc:  # noqa: BLE001 - report and retry
                last_error = exc
                time.sleep(1.5 * attempt)
                continue

            if not result["ok"]:
                last_error = RuntimeError(
                    f"POST {API_PATH} failed: HTTP {result['status']} - {result['text'][:500]}"
                )
                time.sleep(1.5 * attempt)
                continue

            import json

            return json.loads(result["text"])

        raise RuntimeError(f"Failed to fetch event list after {max_retries} attempts") from last_error
