"""Fixed species picker list for the Google Form + species_id lookup for ingest.py.

This is the single source of truth for the Form's six "Pokémon" dropdown
questions (paste SPECIES_LIST's display names into each of them, identically)
and for validating/normalizing each submitted row in ingest.py. Because the
Form only offers these exact choices (no free text), ingest.py can do a
closed-vocabulary lookup instead of fuzzy name matching.

Bootstrapped from every species_id/species_name pair actually used across
real M-B (the current Pokémon Champions regulation as of this writing)
tournament results in ../../vgc-tournament-explorer/data/players/*.json -
i.e. this is what's empirically legal and in play in Pokémon Champions
specifically, not a generic Scarlet/Violet VGC roster (Champions doesn't yet
include everything from SV's DLC - e.g. most box legendaries and Paradox
Pokémon are absent from real usage data, so they're absent here too).

That raw union needed real cleanup before becoming a picker list: it mixes
Limitless-sourced and pokestats.top-sourced rows, so some entries carried
pokestats' own no-separator sprite-slug convention instead of Limitless's
hyphenated one (see limitless_extractor/sprites.py's pokestats_species_slug)
- 'basculegion-f'/'meowstic-f' - handled below. It also had straightforward
typos ('Farigarif', 'Kinggambit', 'Ninetails', 'hydregion' -> the correct
spellings), duplicate entries for one real species under two different
slugs, and a handful of rows where pokestats' scrape apparently picked up a
player's held-item-suffixed nickname instead of the species name (e.g.
'Gholdengo - Life Orb', 'Incineroar - Sitrus Berry', assorted non-English
nicknames like 'Flor Eterna' for Eternal Flower Floette) - all discarded.

Species_id here is deliberately left exactly as scraped (not force-slugified
to a single convention): app.js's sprite rendering tries the Limitless CDN
first and falls back to the pokestats CDN on 404 (same pattern as
vgc-tournament-explorer/dashboard.html's spriteChipHtml), so an id from
either source's native convention resolves correctly regardless of which
CDN actually has that sprite.

Extended with every species that has a Mega Evolution in Pokemon Champions
per https://game8.co/games/Pokemon-Champions/archives/592472 (including
base forms missing from the M-B usage data entirely, like Salamence,
Golisopod and Baxcalibur, and Champions-exclusive "Mega X Z" variants for
Absol, Garchomp and Lucario beyond the standard Mega). Their species_id
slugs are this module's own best-guess convention (e.g. '-mega-z' suffix,
'-f-mega' for a gendered Mega), not verified against a real sprite CDN the
way the M-B-derived entries were - if a sprite 404s on both CDNs for one of
these, the id likely needs a manual override once someone can check
Limitless/pokestats' actual slug for it.

TODO before going live: once M-C's regulation notes are published, do one
more pass to add anything newly legal that wasn't yet used in M-B and isn't
a Mega (this list is still "observed legal + all Megas", not "every
currently legal species") and drop anything M-C removes.
"""

# (display_name, species_id) - display_name is what appears in the Form's
# dropdown choices and in submitted CSV rows; species_id is what's stored/
# published and fed to spriteUrl().
SPECIES_LIST = [
    ('Abomasnow', 'abomasnow'),
    ('Abomasnow-Mega', 'abomasnow-mega'),
    ('Absol', 'absol'),
    ('Absol-Mega', 'absol-mega'),
    ('Absol-Mega-Z', 'absol-mega-z'),
    ('Aegislash', 'aegislash'),
    ('Aegislash Blade Forme', 'aegislash-blade'),
    ('Aerodactyl', 'aerodactyl'),
    ('Aerodactyl-Mega', 'aerodactyl-mega'),
    ('Aggron', 'aggron'),
    ('Aggron-Mega', 'aggron-mega'),
    ('Alakazam', 'alakazam'),
    ('Alakazam-Mega', 'alakazam-mega'),
    ('Alcremie', 'alcremie'),
    ('Alcremie-Ruby-Swirl', 'alcremie-ruby-swirl'),
    ('Alcremie-Salted-Cream', 'alcremie-salted-cream'),
    ('Alolan Ninetales', 'ninetales-alola'),
    ('Alolan Raichu', 'raichu-alola'),
    ('Altaria', 'altaria'),
    ('Altaria-Mega', 'altaria-mega'),
    ('Amoonguss', 'amoonguss'),
    ('Ampharos', 'ampharos'),
    ('Ampharos-Mega', 'ampharos-mega'),
    ('Annihilape', 'annihilape'),
    ('Appletun', 'appletun'),
    ('Araquanid', 'araquanid'),
    ('Arbok', 'arbok'),
    ('Arcanine', 'arcanine'),
    ('Archaludon', 'archaludon'),
    ('Ariados', 'ariados'),
    ('Armarouge', 'armarouge'),
    ('Aromatisse', 'aromatisse'),
    ('Audino', 'audino'),
    ('Audino-Mega', 'audino-mega'),
    ('Aurorus', 'aurorus'),
    ('Avalugg', 'avalugg'),
    ('Azumarill', 'azumarill'),
    ('Banette', 'banette'),
    ('Banette-Mega', 'banette-mega'),
    ('Barbaracle', 'barbaracle'),
    ('Barbaracle-Mega', 'barbaracle-mega'),
    ('Basculegion', 'basculegion'),
    ('Basculegion ♀', 'basculegion-f'),
    ('Bastiodon', 'bastiodon'),
    ('Baxcalibur', 'baxcalibur'),
    ('Baxcalibur-Mega', 'baxcalibur-mega'),
    ('Beartic', 'beartic'),
    ('Beedrill', 'beedrill'),
    ('Beedrill-Mega', 'beedrill-mega'),
    ('Bellibolt', 'bellibolt'),
    ('Blastoise', 'blastoise'),
    ('Blastoise-Mega', 'blastoise-mega'),
    ('Blaziken', 'blaziken'),
    ('Blaziken-Mega', 'blaziken-mega'),
    ('Camerupt', 'camerupt'),
    ('Camerupt-Mega', 'camerupt-mega'),
    ('Castform', 'castform'),
    ('Ceruledge', 'ceruledge'),
    ('Chandelure', 'chandelure'),
    ('Chandelure-Mega', 'chandelure-mega'),
    ('Charizard', 'charizard'),
    ('Charizard-Mega-X', 'charizard-mega-x'),
    ('Charizard-Mega-Y', 'charizard-mega-y'),
    ('Chesnaught', 'chesnaught'),
    ('Chesnaught-Mega', 'chesnaught-mega'),
    ('Chi-Yu', 'chi-yu'),
    ('Chimecho', 'chimecho'),
    ('Chimecho-Mega', 'chimecho-mega'),
    ('Clawitzer', 'clawitzer'),
    ('Clefable', 'clefable'),
    ('Clefable-Mega', 'clefable-mega'),
    ('Cofagrigus', 'cofagrigus'),
    ('Conkeldurr', 'conkeldurr'),
    ('Corviknight', 'corviknight'),
    ('Crabominable', 'crabominable'),
    ('Crabominable-Mega', 'crabominable-mega'),
    ('Decidueye', 'decidueye'),
    ('Dedenne', 'dedenne'),
    ('Delphox', 'delphox'),
    ('Delphox-Mega', 'delphox-mega'),
    ('Diggersby', 'diggersby'),
    ('Ditto', 'ditto'),
    ('Dragalge', 'dragalge'),
    ('Dragalge-Mega', 'dragalge-mega'),
    ('Dragapult', 'dragapult'),
    ('Dragonite', 'dragonite'),
    ('Dragonite-Mega', 'dragonite-mega'),
    ('Drampa', 'drampa'),
    ('Drampa-Mega', 'drampa-mega'),
    ('Eelektross', 'eelektross'),
    ('Eelektross-Mega', 'eelektross-mega'),
    ('Eiscue', 'eiscue'),
    ('Emboar', 'emboar'),
    ('Emboar-Mega', 'emboar-mega'),
    ('Emolga', 'emolga'),
    ('Empoleon', 'empoleon'),
    ('Espathra', 'espathra'),
    ('Espeon', 'espeon'),
    ('Eternal Flower Floette', 'floette-eternal'),
    ('Excadrill', 'excadrill'),
    ('Excadrill-Mega', 'excadrill-mega'),
    ('Falinks', 'falinks'),
    ('Falinks-Mega', 'falinks-mega'),
    ('Fan Rotom', 'rotom-fan'),
    ('Farigiraf', 'farigiraf'),
    ('Feraligatr', 'feraligatr'),
    ('Feraligatr-Mega', 'feraligatr-mega'),
    ('Flapple', 'flapple'),
    ('Flareon', 'flareon'),
    ('Floette', 'floette'),
    ('Floette-Eternal-Flower-Mega', 'floette-eternal-flower-mega'),
    ('Floette-Mega', 'floette-mega'),
    ('Florges', 'florges'),
    ('Forretress', 'forretress'),
    ('Froslass', 'froslass'),
    ('Froslass-Mega', 'froslass-mega'),
    ('Furfrou', 'furfrou'),
    ('Galarian Slowbro', 'slowbro-galar'),
    ('Galarian Slowking', 'slowking-galar'),
    ('Galarian Stunfisk', 'stunfisk-galar'),
    ('Gallade', 'gallade'),
    ('Gallade-Mega', 'gallade-mega'),
    ('Garbodor', 'garbodor'),
    ('Garchomp', 'garchomp'),
    ('Garchomp-Mega', 'garchomp-mega'),
    ('Garchomp-Mega-Z', 'garchomp-mega-z'),
    ('Gardevoir', 'gardevoir'),
    ('Gardevoir-Mega', 'gardevoir-mega'),
    ('Garganacl', 'garganacl'),
    ('Gengar', 'gengar'),
    ('Gengar-Mega', 'gengar-mega'),
    ('Gholdengo', 'gholdengo'),
    ('Gigantamax Grimmsnarl', 'grimmsnarl-gmax'),
    ('Girafarig', 'girafarig'),
    ('Glaceon', 'glaceon'),
    ('Glalie', 'glalie'),
    ('Glalie-Mega', 'glalie-mega'),
    ('Glimmet', 'glimmet'),
    ('Glimmora', 'glimmora'),
    ('Glimmora-Mega', 'glimmora-mega'),
    ('Gliscor', 'gliscor'),
    ('Golisopod', 'golisopod'),
    ('Golisopod-Mega', 'golisopod-mega'),
    ('Golurk', 'golurk'),
    ('Golurk-Mega', 'golurk-mega'),
    ('Goodra', 'goodra'),
    ('Gothitelle', 'gothitelle'),
    ('Gourgeist', 'gourgeist'),
    ('Greninja', 'greninja'),
    ('Greninja-Mega', 'greninja-mega'),
    ('Grimmsnarl', 'grimmsnarl'),
    ('Gyarados', 'gyarados'),
    ('Gyarados-Mega', 'gyarados-mega'),
    ('Hatterene', 'hatterene'),
    ('Hawlucha', 'hawlucha'),
    ('Hawlucha-Mega', 'hawlucha-mega'),
    ('Heat Rotom', 'rotom-heat'),
    ('Heliolisk', 'heliolisk'),
    ('Heracross', 'heracross'),
    ('Heracross-Mega', 'heracross-mega'),
    ('Hippowdon', 'hippowdon'),
    ('Hisuian Arcanine', 'arcanine-hisui'),
    ('Hisuian Avalugg', 'avalugg-hisui'),
    ('Hisuian Decidueye', 'decidueye-hisui'),
    ('Hisuian Goodra', 'goodra-hisui'),
    ('Hisuian Sneasel', 'sneasel-hisui'),
    ('Hisuian Typhlosion', 'typhlosion-hisui'),
    ('Hisuian Zoroark', 'zoroark-hisui'),
    ('Hitmontop', 'hitmontop'),
    ('Houndoom', 'houndoom'),
    ('Houndoom-Mega', 'houndoom-mega'),
    ('Houndstone', 'houndstone'),
    ('Hydrapple', 'hydrapple'),
    ('Hydreigon', 'hydreigon'),
    ('Incineroar', 'incineroar'),
    ('Indeedee', 'indeedee'),
    ('Indeedee ♀', 'indeedee-f'),
    ('Infernape', 'infernape'),
    ('Inteleon', 'inteleon'),
    ('Jolteon', 'jolteon'),
    ('Kangaskhan', 'kangaskhan'),
    ('Kangaskhan-Mega', 'kangaskhan-mega'),
    ('Kingambit', 'kingambit'),
    ('Kingdra', 'kingdra'),
    ('Kleavor', 'kleavor'),
    ('Klefki', 'klefki'),
    ('Kommo-o', 'kommo-o'),
    ('Krookodile', 'krookodile'),
    ('Leafeon', 'leafeon'),
    ('Liepard', 'liepard'),
    ('Lilligant', 'lilligant'),
    ('Lopunny', 'lopunny'),
    ('Lopunny-Mega', 'lopunny-mega'),
    ('Lucario', 'lucario'),
    ('Lucario-Mega', 'lucario-mega'),
    ('Lucario-Mega-Z', 'lucario-mega-z'),
    ('Ludicolo', 'ludicolo'),
    ('Luxray', 'luxray'),
    ('Lycanroc', 'lycanroc'),
    ('Lycanroc Dusk', 'lycanroc-dusk'),
    ('Lycanroc Midnight', 'lycanroc-midnight'),
    ('Machamp', 'machamp'),
    ('Malamar', 'malamar'),
    ('Malamar-Mega', 'malamar-mega'),
    ('Mamoswine', 'mamoswine'),
    ('Manectric', 'manectric'),
    ('Manectric-Mega', 'manectric-mega'),
    ('Maushold', 'maushold'),
    ('Mawile', 'mawile'),
    ('Mawile-Mega', 'mawile-mega'),
    ('Medicham', 'medicham'),
    ('Medicham-Mega', 'medicham-mega'),
    ('Meganium', 'meganium'),
    ('Meganium-Mega', 'meganium-mega'),
    ('Meowscarada', 'meowscarada'),
    ('Meowstic', 'meowstic'),
    ('Meowstic ♀', 'meowstic-f'),
    ('Meowstic ♀-Mega', 'meowstic-f-mega'),
    ('Meowstic-Mega', 'meowstic-mega'),
    ('Metagross', 'metagross'),
    ('Metagross-Mega', 'metagross-mega'),
    ('Milotic', 'milotic'),
    ('Mimikyu', 'mimikyu'),
    ('Morpeko', 'morpeko'),
    ('Mow Rotom', 'rotom-mow'),
    ('Mr. Rime', 'mr-rime'),
    ('Mudsdale', 'mudsdale'),
    ('Musharna', 'musharna'),
    ('Ninetales', 'ninetales'),
    ('Noivern', 'noivern'),
    ('Octillery', 'octillery'),
    ('Ogerpon-Hearthflame', 'ogerpon-hearthflame'),
    ('Oranguru', 'oranguru'),
    ('Orthworm', 'orthworm'),
    ('Overqwil', 'overqwil'),
    ('Palafin', 'palafin'),
    ('Palafin-Hero', 'palafin-hero'),
    ('Paldean Tauros', 'tauros-paldea'),
    ('Paldean Tauros Aqua Breed', 'tauros-paldea-aqua'),
    ('Paldean Tauros Blaze Breed', 'tauros-paldea-blaze'),
    ('Pangoro', 'pangoro'),
    ('Passimian', 'passimian'),
    ('Pawmot', 'pawmot'),
    ('Pelipper', 'pelipper'),
    ('Pidgeot', 'pidgeot'),
    ('Pidgeot-Mega', 'pidgeot-mega'),
    ('Pikachu', 'pikachu'),
    ('Pinsir', 'pinsir'),
    ('Pinsir-Mega', 'pinsir-mega'),
    ('Politoed', 'politoed'),
    ('Polteageist', 'polteageist'),
    ('Primarina', 'primarina'),
    ('Pyroar', 'pyroar'),
    ('Pyroar-Mega', 'pyroar-mega'),
    ('Quaquaval', 'quaquaval'),
    ('Qwilfish', 'qwilfish'),
    ('Raichu', 'raichu'),
    ('Raichu-Mega-X', 'raichu-mega-x'),
    ('Raichu-Mega-Y', 'raichu-mega-y'),
    ('Rampardos', 'rampardos'),
    ('Reuniclus', 'reuniclus'),
    ('Rhyperior', 'rhyperior'),
    ('Rillaboom', 'rillaboom'),
    ('Roserade', 'roserade'),
    ('Rotom', 'rotom'),
    ('Rotom-Frost', 'rotom-frost'),
    ('Runerigus', 'runerigus'),
    ('Sableye', 'sableye'),
    ('Sableye-Mega', 'sableye-mega'),
    ('Salamence', 'salamence'),
    ('Salamence-Mega', 'salamence-mega'),
    ('Salazzle', 'salazzle'),
    ('Samurott', 'samurott'),
    ('Samurott-Hisui', 'samurott-hisui'),
    ('Sandaconda', 'sandaconda'),
    ('Sceptile', 'sceptile'),
    ('Sceptile-Mega', 'sceptile-mega'),
    ('Scizor', 'scizor'),
    ('Scizor-Mega', 'scizor-mega'),
    ('Scolipede', 'scolipede'),
    ('Scolipede-Mega', 'scolipede-mega'),
    ('Scovillain', 'scovillain'),
    ('Scovillain-Mega', 'scovillain-mega'),
    ('Scrafty', 'scrafty'),
    ('Scrafty-Mega', 'scrafty-mega'),
    ('Serperior', 'serperior'),
    ('Shadow Rider Calyrex', 'calyrex-shadow-rider'),
    ('Sharpedo', 'sharpedo'),
    ('Sharpedo-Mega', 'sharpedo-mega'),
    ('Simipour', 'simipour'),
    ('Simisage', 'simisage'),
    ('Simisear', 'simisear'),
    ('Sinistcha', 'sinistcha'),
    ('Sinistea', 'sinistea'),
    ('Skarmory', 'skarmory'),
    ('Skarmory-Mega', 'skarmory-mega'),
    ('Skeledirge', 'skeledirge'),
    ('Slowbro', 'slowbro'),
    ('Slowbro-Mega', 'slowbro-mega'),
    ('Slowking', 'slowking'),
    ('Slurpuff', 'slurpuff'),
    ('Sneasler', 'sneasler'),
    ('Snorlax', 'snorlax'),
    ('Spiritomb', 'spiritomb'),
    ('Staraptor', 'staraptor'),
    ('Staraptor-Mega', 'staraptor-mega'),
    ('Starmie', 'starmie'),
    ('Starmie-Mega', 'starmie-mega'),
    ('Steelix', 'steelix'),
    ('Steelix-Mega', 'steelix-mega'),
    ('Stunfisk', 'stunfisk'),
    ('Swampert', 'swampert'),
    ('Swampert-Mega', 'swampert-mega'),
    ('Sylveon', 'sylveon'),
    ('Talonflame', 'talonflame'),
    ('Tauros', 'tauros'),
    ('Thundurus', 'thundurus'),
    ('Tinkaton', 'tinkaton'),
    ('Torkoal', 'torkoal'),
    ('Torterra', 'torterra'),
    ('Toucannon', 'toucannon'),
    ('Toxapex', 'toxapex'),
    ('Toxicroak', 'toxicroak'),
    ('Trevenant', 'trevenant'),
    ('Tropius', 'tropius'),
    ('Tsareena', 'tsareena'),
    ('Typhlosion', 'typhlosion'),
    ('Tyranitar', 'tyranitar'),
    ('Tyranitar-Mega', 'tyranitar-mega'),
    ('Tyrantrum', 'tyrantrum'),
    ('Umbreon', 'umbreon'),
    ('Vanilluxe', 'vanilluxe'),
    ('Vaporeon', 'vaporeon'),
    ('Venusaur', 'venusaur'),
    ('Venusaur-Mega', 'venusaur-mega'),
    ('Vespiquen', 'vespiquen'),
    ('Victreebel', 'victreebel'),
    ('Victreebel-Mega', 'victreebel-mega'),
    ('Vileplume', 'vileplume'),
    ('Vivillon', 'vivillon'),
    ('Volcarona', 'volcarona'),
    ('Wash Rotom', 'rotom-wash'),
    ('Watchog', 'watchog'),
    ('Weavile', 'weavile'),
    ('Whimsicott', 'whimsicott'),
    ('Wyrdeer', 'wyrdeer'),
    ('Zoroark', 'zoroark'),
]

# Case-insensitive display-name -> species_id, used by ingest.py to validate
# and normalize each of the 6 species cells in a submitted row.
SPECIES_NAME_TO_ID = {name.strip().lower(): species_id for name, species_id in SPECIES_LIST}

# display_name -> (species_id, species_name) for JSON output, keyed the same way.
SPECIES_NAME_TO_ENTRY = {
    name.strip().lower(): (species_id, name) for name, species_id in SPECIES_LIST
}


def lookup_species(raw_name):
    """Resolve a Form-submitted species string to (species_id, species_name).

    Returns None if it doesn't match any entry in SPECIES_LIST - since the
    Form only offers these exact choices, an unrecognized value means either
    a manual Sheet edit or the list going stale, not normal input.
    """
    if not raw_name:
        return None
    return SPECIES_NAME_TO_ENTRY.get(raw_name.strip().lower())
